resolver: lts-20.16
compiler: ghc-9.2.7
allow-newer: true
packages:
        - .
extra-deps:
- diagrams-core-1.5.0.1
- diagrams-lib-1.4.5.3
- diagrams-rasterific-1.4.2.2
- monoid-extras-0.6
- active-0.2.0.16
- dual-tree-0.2.3.1
- colour-2.3.6
- fsnotify-0.4.0.0
- lens-5.2
- svg-builder-0.1.1
